proyectx/config/routes.rb
Rails.application.routes.draw do
resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

proyectx/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyectx/app/models/document.rb
class Document < ApplicationRecord
    has_many :people
end

proyectx/app/models/person.rb
class Person < ApplicationRecord
  belongs_to :document
  belongs_to :role
end

proyectx/app/models/role.rb
class Role < ApplicationRecord
    has_many :people
end

proyectx/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

proyectx/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end
 
  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      flash[:notice] = "El Registro Se a Guardado"
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def update
     @person = Person.find(params[:id])
      if @person.update(person_params)
        redirect_to person_path (@person)
      else
        render :edit
      end
    end
  


  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:identification, :first_name, :second_name, :first_last_name, :second_last_name, :role_id, :document_id)
    end
  end

proyectx/app/helpers/application_helper.rb
module ApplicationHelper
end

proyectx/app/helpers/people_helper.rb
module PeopleHelper
end

proyectx/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyectx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
       
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
       
  </head>

  <body>
  <nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

proyectx/app/views/people/_form.html.erb
<%= simple_form_for(@person) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    
    <div class="form-outline mb-4">
      <%= f.input :identification %>
    </div>
    <div class="form-outline mb-4">
      <%= f.input :first_name %>
    </div>
    <div class="form-outline mb-4">
      <%= f.input :second_name %>
    </div>
    <div class="form-outline mb-4">
      <%= f.input :first_last_name %>
    </div>
    <div class="form-outline mb-4"> 
      <%= f.input :second_last_name %>
    </div>
    <div class="form-outline mb-4 ">
      <%= f.association :role  , label_method: :role_name %>
    </div>
    <div class="form-outline mb-4 " >
      <%= f.association :document, label_method: :document_type %>
    </div>
    <div class="btn btn-primary btn-block mb-4">
      <%= f.button :submit %>
    </div>
  <% end %>

proyectx/app/views/people/create.html.erb
<h1>People</h1>

proyectx/app/views/people/edit.html.erb
<center>
<h1>Editar Persona</h1>
<%= render 'form', person: @person %>
<%= link_to 'Show', @person %> |
<%= link_to 'Volver', people_path %>
</center>

proyectx/app/views/people/index.html.erb
<center><h1> Formulario De Personas </h1>
<table class="table table-hover">
  <thead>
    <tr>
    <th scope="col">Identification</th>
    <th scope="col">First Name</th>
    <th scope="col">Second Name</th>
    <th scope="col">First Last Name</th>
    <th scope="col">Second Last Name</th>
    <th>Role</th>
    <th>Document</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @people.each do |person| %>
        <td><%= person.identification %></td>
          <td><%= person.first_name %></td>
           <td><%= person.second_name %></td>
           <td><%= person.first_last_name %></td>
          <td><%= person.second_last_name %></td>
        <td><%= person.role.role_name %></td>
      <td><%= person.document.document_type %></td>
        
    </tr>
    <% end %>
  </tbody>
</table>

proyectx/app/views/people/new.html.erb
<center>
<h1>Nueva Persona</h1>
<%= render 'form', person: @person %>
<%= link_to 'Volver', people_path %>

</center>

proyectx/app/views/people/show.html.erb
<p>
  <strong>Identification:</strong>
  <%= @person.identification %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Second Name:</strong>
  <%= @person.second_name %>
</p>

<p>
  <strong>First Last Name:</strong>
  <%= @person.first_last_name %>
</p>

<p>
  <strong>Second Last Name:</strong>
  <%= @person.second_last_name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @person.role.role_name %>
</p>

<p>
  <strong>Document:</strong>
  <%= @person.document.document_type %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Volver', people_path %>